// ---- SSdotr: cleanup defines ----

#undef DOTR_CHECK_INTERVAL
#undef DOTR_PLAYER_ZONE_RANGE
#undef DOTR_SPAWN_EDGE_RANGE
#undef DOTR_MAX_PHYSICAL_PER_ZONE
#undef DOTR_VIRTUAL_STEP_TICKS
#undef DOTR_DEVIRT_COOLDOWN
#undef DOTR_SAFE_RANGE
#undef DOTR_WITHER_DPS
#undef DOTR_VIRTUAL_CHASE_TIMEOUT
#undef DOTR_DEBUG
