// ---- Necromantic Monolith: cleanup defines ----

#undef NECROMONOLITH_BUILD_TIME
#undef NECROMONOLITH_SPAWN_INTERVAL
#undef NECROMONOLITH_MIN_SPAWN
#undef NECROMONOLITH_MAX_SPAWN
#undef NECROMONOLITH_DESIRED_ROUTES
#undef NECROMONOLITH_ROUTE_DEPTH
#undef NECROMONOLITH_MAX_MINIONS
#undef NECROMONOLITH_MINION_LIFETIME
#undef NECROMONOLITH_CHASE_TIMEOUT
#undef NECROMONOLITH_CHASE_LEASH_DISTANCE
#undef NECROMONOLITH_TARGET_ROUTE_LEASH_DISTANCE
#undef NECROMONOLITH_ROUTE_WINDOW
#undef NECROMONOLITH_REENGAGE_COOLDOWN
#undef NECROMONOLITH_ROUTE_VALIDATE_EVERY
#undef NECROMONOLITH_WAVES_PER_REST
#undef NECROMONOLITH_STUCK_WALL_CLIMB_TICKS
#undef NECROMONOLITH_WALL_CLIMB_COOLDOWN
#undef NECROMONOLITH_WALL_CLIMB_TIME
#undef NECROMONOLITH_DEBUG
