// Undef point for bonds module macros.
// Intended include target after the module's compile section:
// #include "modular_twilight_axis\bonds_module\bonds_module_deinclude.dm"

#undef BOND_WARMTH_MIN
#undef BOND_WARMTH_MAX
#undef BOND_WEIGHT_MIN
#undef BOND_WEIGHT_MAX

#undef BOND_MAX_PER_MIND
#undef BOND_COMMIT_COOLDOWN
#undef BOND_MAX_HISTORY
#undef BOND_VISIBLE_WEIGHT

#undef BOND_COMMIT_FALLOFF
#undef BOND_KILL_ATTRIBUTION_WINDOW

#undef BOND_TAG_NONE
#undef BOND_TAG_SHED_BLOOD
#undef BOND_TAG_KILLED_ME
#undef BOND_TAG_KILLED_THEM
#undef BOND_TAG_COMFORTED
#undef BOND_TAG_SERVED_TOGETHER
#undef BOND_TAG_OWES_DEBT

#undef BOND_MAX_SEEDS
#undef BOND_SEED_DELAY
#undef BOND_SEED_RETRY

#undef BOND_CATEGORY_VIOLENCE
#undef BOND_CATEGORY_KINDNESS
#undef BOND_CATEGORY_DEATH
#undef BOND_CATEGORY_SEED

#undef BOND_FACTION_NOBLE
#undef BOND_FACTION_COURT
#undef BOND_FACTION_RETINUE
#undef BOND_FACTION_GARRISON
#undef BOND_FACTION_CITYWATCH
#undef BOND_FACTION_VANGUARD
#undef BOND_FACTION_CHURCH
#undef BOND_FACTION_INQUISITION
#undef BOND_FACTION_BURGHER
#undef BOND_FACTION_ATC
#undef BOND_FACTION_PEASANT
#undef BOND_FACTION_SIDEFOLK
#undef BOND_FACTION_WANDERER
#undef BOND_FACTION_OUTLAW

#undef BOND_STANCE_SAME_FACTION_WARMTH
#undef BOND_STANCE_AFFINITY_THRESHOLD
#undef BOND_MAP_MIN_WEIGHT
#undef BOND_HOUSE_PROPAGATION
#undef BOND_INFLUENCE_POOL
#undef BOND_INFLUENCE_BAN
#undef BOND_INFLUENCE_REFILL

#undef BOND_KIN_PARENT
#undef BOND_KIN_CHILD
#undef BOND_KIN_SPOUSE
#undef BOND_KIN_FORMER_SPOUSE
#undef BOND_KIN_SWORN_SIBLING

#undef BOND_GROUP_FAMILY
#undef BOND_GROUP_KNOWN
#undef BOND_GROUP_WARM
#undef BOND_GROUP_COLD
#undef BOND_GROUP_HOSTILE

#undef BONDLOG_DEBUG
#undef BONDLOG_INFO
#undef BONDLOG_WARN
#undef BONDLOG_ERROR

#ifdef BONDS_DEBUG_LOGGING
#undef BONDS_DEBUG_LOGGING
#endif
