// ---- SSdort: cleanup defines ----

#undef DORT_CHECK_INTERVAL
#undef DORT_PLAYER_ZONE_RANGE
#undef DORT_SPAWN_EDGE_RANGE
#undef DORT_MAX_PHYSICAL_PER_ZONE
#undef DORT_VIRTUAL_STEP_TICKS
#undef DORT_DEVIRT_COOLDOWN
#undef DORT_SAFE_RANGE
#undef DORT_WITHER_DPS
#undef DORT_VIRTUAL_CHASE_TIMEOUT
#undef DORT_DEBUG
